### ISSUE TITLE
Add a path to return a knowledge map

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/translator-knowledge-beacon#40]
with @stevencox @balhoff @jmcmurry 

For smartapi and beacons we will define a way a knowledge source can advertise what types and identifiers are related by what relations/predicates.

This would be a list such as the following

```
-
  subject:
    semantic_type: gene
    prefixes:
       - NCBIGene
       - ENSEMBL
       - HGNC
       - MGI
  predicate:
    id: RO:nnn
    label: has phenotype
  object:
    semantic_type: phenotype
    prefixes:
       - MP
       - HP
  count: 500 # optional
  description: >
     blah blah
-
  ...      
```

**Comment by cbizon** [comment]
This is good and should go a long way towards helping the reasoner teams.  Vlado and I showed an example of how the yaml for one of the biolink endpoints could be annotated like this.

I am still struggling a little with the object prefixes.  The idea is that these are "might get" prefixes.  You can't know ahead of time which of them you will get.   So if a reasoner is planning a set of calls, it has to anticipate dealing with all of the possibilities.  That probably means calling an identifier translation service in between the output of one call and the input of the next (think PIKR or OXO).  

So how would the yaml above describe one of these ID translators?  Usually they take any kind of id (for one or more entity) and return all the kinds of IDs for that object that it knows about.  So if I had a gene ID service I would get

```
subject:
  prefixes:
    - NCBIGene
    - ENSEMBLE
    - HGNC
 ...
object:
  prefixes:
    - NCBIGene
    - ENSEMBLE
    - HGNC
```

But here the output prefixes are not "might gets" but "will give you these if I have them".

Again, the reason that this is important is in trying to plan a path through sources/IDs ahead of time.  If the identifier service above can only tell me that it might give me HGNC ids, then it doesn't help me any in the planning.  I can imagine 3 ways around this:

1. modify the yaml above somehow to distinguish between these cases (maybe an annotation for required prefixes?)

2. If we want to use a service like OXO, wrap it in a service that we stand up that implements a bunch of endpoints like NCBIGeneToHGNC, and then annotate those endpoints (this is our current solution)

3. Treat ID translation as a separate activity from Knowledge Source querying.  I don't think this is very elegant, but it would probably work.

Sorry for the long comment...

**Comment by micheldumontier** [comment]
one option is for us to specify a triple-based metamap, in which we have subject type, relation, object type so that we maintain the relationship between subject and object types e.g. 
- subjectype: drug
  relation: treats
  objecttype: disease

alternatively, we can specify this relation with the more precise identifier type that holds the relation e.g
- subjecttype: drugbank
  relation: treats
  objectype: doid

if we have a mapping between drugbank and drug, and doid and disease, then we get back to the first declaration. if we go with the first option, then we would get a list of all possible drug and disease identifier types.

**Comment by cmungall** [comment]
- [ ] extend yaml swagger (Richard)
 - [ ] ensure implemented in existing beacons (Lance)

**Comment by cmungall** [comment]
@cbizon - ok, so if each path object represents a potential path through semantic types, it could additionally be annotated by ID paths within that concept path, such as in the following

```
-
  subject:
    semantic_type: gene
    prefixes:
       - NCBIGene
       - ENSEMBL
       - HGNC
       - MGI
  predicate:
    id: RO:nnn
    label: has phenotype
  object:
    semantic_type: phenotype
    prefixes:
       - MP
       - HP
  idpaths:
    -
      subj: MGI
      obj: MP
    -
      subj: HGNC
      obj: WP
   -
      subj: ENSEMBL
      obj: HP
   -
      subj: ENSEMBL
      obj: MP
  count: 500 # optional
```

here we are saying that for a gene-phenotype path, if you give an MGI you will get an MP, and if you give an HGNC you get an HP. However, if you give an ENSEMBL then you can either get an HP or MP. There are a variety of ways a planner can infer whether the result will be which (based on species of the input, knowledge that the root node of each ontology is for a respective species, and that has-phenotype is generally species-preserving) but this is probably out of scope.
